BASE_URL_FRONT = 'https://foodgram-frontend-1.prakticum-team.ru'
BASE_URL_BACK = 'https://foodgram-backend-1.prakticum-team.ru'
SIGNIN_PAGE = '/signin'
SIGNUP_PAGE = '/signup'
RECIPIES_PAGE = '/recipes'
CREATE_RECIPIE_PAGE = '/recipes/create'
RECIPIE_DETAILS_PAGE = '/recipes/'